### ISSUE TITLE
The annotation \u0022@RouteScope\u0022 in class Frosh\\Tools\\Controller\\CacheController was never imported

### ISSUE THREAD

**Issue by SwissCommerce** [FriendsOfShopware/FroshTools#103]
### PHP Version

8.0.22

### Shopware Version

6.4.14.0

### Actual behaviour

{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"[Semantical Error] The annotation \u0022@RouteScope\u0022 in class Frosh\\Tools\\Controller\\CacheController was never imported. Did you maybe forget to add a \u0022use\u0022 statement for this annotation? in \/home\/www-data\/XXXXX\/vendor\/store.shopware.com\/froshtools\/src\/Resources\/config\/..\/..\/Controller (which is being imported from \u0022\/home\/www-data\/XXXXX\/vendor\/store.shopware.com\/froshtools\/src\/Resources\/config\/routes.xml\u0022). Make sure to use PHP 8+ or that annotations are installed and enabled."}]}

### Expected behaviour

Plugin runs

### Steps to Reproduce?

Update the plugin to the newest version 0.2.4 and run plugin:update

- Cache is cleared (rm -rf and cache:clear)
- No redis or other caches are used

Very odd behavior. Controller and xml loook fine to me

**Comment by shyim** [comment]
Can you just run `cache:clear` ?

**Comment by SwissCommerce** [comment]
Weird, ok this works. I added the rm -rf to our alias to be save. 

Since when is this an issue? Whats the cause of it?

**Comment by shyim** [comment]
Its some weird issue with opcache
