### ISSUE TITLE
Passing detail data to QueueChecker & TaskChecker

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfShopware/FroshTools#104]
### Please describe the feature you would like to see implemented.

Having the queue and scheduled task being checked is very nice, but it would be good to have more info in these checks to take action or add a specific alert message to e.g. a monitoring.

This would mostly apply to these two since they deal with actual **data**, whereas the rest of the checks is more **config** related.

Here is an example (could be data or entities)

![image](https://user-images.githubusercontent.com/8600299/185554158-bc1263b0-bf0d-4d85-8eb5-ecac013e3c46.png)

This should / could apply for 

```
private const WARNING = 'STATE_WARNING';
private const ERROR = 'STATE_ERROR';
```

Questions being:

1. Add the data array to the SettingsResult struct for all to be accessible or have a solution for Task and Queue only ?
2. Would a PR like this be accepted? Or is it out of scope?

**Comment by shyim** [comment]
Hey,

it's a cool idea. But I would like to have a parameter like `?extended=1`

That controller action is often called, by the admin icon and don't need that information 🤔

**Comment by Isengo1989** [comment]
Yep, that makes sense. I will create a PR.
