### ISSUE TITLE
Webhook integration

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfShopware/FroshTools#105]
### Please describe the feature you would like to see implemented.

We do use New Relic or Tideways for our APM - but many shops can not / do not want to afford that. It would be nice to have a new component **Webhook** or **Alert** which is using an interface to use a simple:

- webhookUrl (config required)
- text (auto generated)
- icon (config optional)

This is then integrated in the queue and task health check and can be configured in the plugin config as followed:

**froshtoolsWebhookUrl**

e.g. Google Chat 
https://chat.googleapis.com/v1/spaces/XXXXXXXXX/messages?key=XXXXXXXXXXXXXXXX-WEfRq3CPzqKqqsHI&token=VQPe-XXXXXXXXXXXXXXXXX%3D

e.g. Slack
https://hooks.slack.com/services/XXXX/XXXXX/gwvjCmbDxxxxx9teZjRXH5

**froshtoolsWebhookImage**

e.g. Google Chat 
https://www.iconpacks.net/icons/2/free-click-icon-2384-thumb.png

e.g. Slack
blue_heart

Questions being

1. Is this a feature being interesting / in the scope of the plugin?

I would create a PR if this is upvoted or discussed

**Comment by shyim** [comment]
to be honest, I did not  really understand what you want to achieve 🤔

**Comment by Isengo1989** [comment]
To add a simple alerting in form of a webhook to the plugin.

So if the healthcheck for schedules task fails a webhook is called to create a simple message like

"Some of your scheduled tasks have failed for the past 10 minutes"

**Comment by shyim** [comment]
The problem I see there is only that, you need a functional queue for reporting that :) 
So when the queue is not working, you will not get a report as your trigger is not working 😂

**Comment by Isengo1989** [comment]
Hmm, now I am not sure what you mean by that :thinking: 

https://github.com/FriendsOfShopware/FroshTools/blob/9e529ae0284d2788349fb27ab6a35eedcb7acca3/src/Components/Health/Checker/HealthChecker/QueueChecker.php#L29

https://github.com/FriendsOfShopware/FroshTools/blob/9e529ae0284d2788349fb27ab6a35eedcb7acca3/src/Components/Health/Checker/HealthChecker/TaskChecker.php#L55

Adding it after setting the warning would be enough and called without a functional queue, no?

**Offtopic**:

I remember there was a question about when the RabbitMQ Support will come for this part -> https://github.com/FriendsOfShopware/FroshTools/blob/9e529ae0284d2788349fb27ab6a35eedcb7acca3/src/Components/Health/Checker/HealthChecker/QueueChecker.php#L23 and there will be a different implementation in 6.5 and therefor not prio now. Did I dream this or was there a slack / github thread on that? :laughing:

**Comment by tinect** [comment]
Hey @Isengo1989 
I think what @shyim means is: when your messenger is down, the webhook won't be called, too.
To be sure: you want a died system to tell others that it's dead 🤔 

I'd recommend you to call the api of froshtools. 🤔

**Comment by Isengo1989** [comment]
@tinect @shyim see the above mentiond code lines. Adding a simple curl request there that can be configured with a URL and a Message.

Since the queuechecker and taskchecker do not need a running queue or messenger (I guess you mean messenger:consumer?) this would work anyways (the health check is called when the admin is open or it is called from outside via controller)

![2022-10-03_15-17](https://user-images.githubusercontent.com/8600299/193587758-3a4ec54d-788f-4e55-9160-0aaf3c42adb3.png)

![2022-10-03_15-17_1](https://user-images.githubusercontent.com/8600299/193587839-bb307675-0436-477c-87f7-743d0d59b086.png)

![2022-10-03_15-18](https://user-images.githubusercontent.com/8600299/193587868-1115024e-0740-48a4-9b9b-42377d72777e.png)

**Comment by tinect** [comment]
Then anyone would have to be loggedin in admin 24/7 so that the status is queued. 🤔

**Comment by Isengo1989** [comment]
It was just an idea "Is this a feature being interesting / in the scope of the plugin?" 

Next time maybe say from the beginning "not wanted" - saves all of us some time ;)

**Comment by shyim** [comment]
I guess that could be cool, to have something like Alerts.

The only problems I see is:

-  When you want to track the Queue. You should not depend on the queue. When the Queue is broken, your own check which uses the queue does not run.
  - Like a Cron URL/Command/Heartbeat in the Storefront
- The alerts needs to be somehow configurable and available for a certain messengers 😅
