### ISSUE TITLE
add event to add specific files to ignored in ShopwareFilesChecker

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshTools#115]
### Please describe the feature you would like to see implemented.

When using composer-patches, there may be some annoying files reported. We could add an Event where these users can subscribe to add their own files to be ignored.

Maybe within isIgnoredFileHash:
https://github.com/FriendsOfShopware/FroshTools/blob/e8fcd0c9019ff49253c8e3921de072f0cda9397e/src/Controller/ShopwareFilesController.php#L128

**Comment by shyim** [comment]
nahh thats an anti pattern for our shopware support. They look explictly there to see if someone did core changes

**Comment by tinect** [comment]
Okay.... I agree... totally... hmm, damn....

I had the situation, my colleague wanted to click onto the restore button :-( 
Could we mark the specific files additionally? 🤔 I'm thinking of something like `isMarkedIntended` and then we would mark the line green and add action like "is marked as intended" as information, f.e.
