### ISSUE TITLE
Scheduled tasks manager and shopware file checker are not working properly after Shopware update to 6.4.15.1

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshTools#116]
### PHP Version

8.0.20

### Shopware Version

6.4.15.1

### Actual behaviour

1. Scheduled Tasks Manager:
These tasks stop and do not run properly either. They do not continue to run even after the manual start.
shopware.invalidate_cache
shopware.elasticsearch.create.alias
Other tasks are running correct.

2. Shopware File Checker
When calling the shopware file checker the content does not load.

These errors appear in developer console
GET https://mydomain.de/api/_action/frosh-tools/shopware-files 500
frosh-tools.js?166391240085897:1 Uncaught (in promise) r {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}

### Expected behaviour

Everything was working with the shopware version 6.4.14.0.

### Steps to Reproduce?

Call up both tabs "Scheduled Tasks Manager" and "Shopware File Checker.

**Comment by tinect** [comment]
Hi @getnatalia,
please note, that not running task are not valid for issue to FroshTools. Please see issue at shopware/platform.

Regarding `Shopware File Checker`, could you please check and send the related logs for the request?

Thank you.
Best Regards,
Sebastian

**Comment by getnatalia** [comment]
Hi Sebastian,

thanks. I already opened an issue at shopware/platform for running tasks.

Here is the log for shopware file checker:

Uncaught PHP Exception TypeError: "Frosh\Tools\Controller\ShopwareFilesController::getOriginalFileContent(): Return value must be of type ?string, bool returned" at vendor/store.shopware.com/froshtools/src/Controller/ShopwareFilesController.php line 125 {"exception":"[object] (TypeError(code: 0): Frosh\\Tools\\Controller\\ShopwareFilesController::getOriginalFileContent(): Return value must be of type ?string, bool returned at vendor/store.shopware.com/froshtools/src/Controller/ShopwareFilesController.php:125)"} []

**Comment by getnatalia** [comment]
I have a suggestion for improvement. We have not activated elastic search at all. So, the associated task shopware.elasticsearch.create.alias should better not appear in tools tasks overview. I think with the second last shopware version  a check for elastic search task was added, to run only if elastic search is enabled. Could you please check this?

**Comment by shyim** [comment]
If you are using composer to manage Shopware. Just run `composer remove shopware/platform`. The task will be deleted then :)

**Comment by getnatalia** [comment]
I've just tested and tried to remove elastic search with composer. Unfortunately, tools has a dependency on elastic search. Here is the error message. 

"The service "Frosh\Tools\Components\Elasticsearch\EsProductDefinition" has a dependency on a non-existent service "Shopware\Elasticsearch\Product\ElasticsearchProductDefinition".

So I can't use tools without elastic search plugin.

**Comment by tinect** [comment]
We separated it into two new issues. Please track these.

Therefore, we close this one.
