### ISSUE TITLE
Shopware file checker shows modified files after update to 6.4.16.0 and frosh tools to 0.2.7

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshTools#130]
### PHP Version

8.0.20

### Shopware Version

6.4.16.0

### Actual behaviour

Shopware file checker shows

`<div role="alert" class="sw-alert sw-alert--default sw-alert--warning sw-alert--icon" style="box-sizing: border-box; margin: 0px auto 20px; padding: 0px; color-scheme: light; border: 1px solid rgb(255, 152, 0); border-radius: 4px; color: rgb(230, 81, 0); background-color: rgb(255, 243, 224); text-align: left; position: relative; font-size: 16px; font-family: &quot;Source Sans Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sw-alert__body sw-alert__body--icon" style="box-sizing: border-box; margin: 0px; padding: 24px 60px; color-scheme: light; line-height: 1.5625;"><div class="sw-alert__message" style="box-sizing: border-box; margin: 0px; padding: 0px; color-scheme: light;">There are modified files</div></div></div><div class="sw-data-grid is--compact sw-data-grid--actions" style="box-sizing: border-box; margin: 0px; padding: 0px; color-scheme: light; overflow: hidden; background-color: rgb(255, 255, 255); color: rgb(82, 102, 122); font-family: &quot;Source Sans Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="sw-data-grid__wrapper" style="box-sizing: border-box; margin: 0px; padding: 0px; color-scheme: light; overflow: auto;">

Name | Status |  
-- | -- | --
vendor/shopware/administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-list-item/sw-cms-list-item.scss | File has been modified |  
vendor/shopware/administration/Resources/app/administration/src/module/sw-cms/page/sw-cms-list/sw-cms-list.html.twig | File has been modified |  
vendor/shopware/administration/Resources/public/static/js/app.js | File has been modified |  
vendor/shopware/core/Content/Category/Aggregate/CategoryTranslation/CategoryTranslationDefinition.php | File has been modified |  
vendor/shopware/core/Framework/Api/ApiDefinition/Generator/EntitySchemaGenerator.php | File has been modified |  
vendor/shopware/core/Framework/Api/ApiDefinition/Generator/OpenApi/OpenApiDefinitionSchemaBuilder.php | File has been modified |  
vendor/shopware/core/Framework/DataAbstractionLayer/Field/JsonField.php | File has been modified |  
vendor/shopware/core/Framework/DependencyInjection/CompilerPass/TwigLoaderConfigCompilerPass.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/autoload.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/ClassLoader.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/InstalledVersions.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_classmap.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_files.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_namespaces.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_psr4.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_real.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/autoload_static.php | File has been modified |  
vendor/shopware/recovery/Common/vendor/composer/installed.php | File has been modified |  
vendor/shopware/recovery/vendor/autoload.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/ClassLoader.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/InstalledVersions.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_classmap.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_files.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_namespaces.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_psr4.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_real.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/autoload_static.php | File has been modified |  
vendor/shopware/recovery/vendor/composer/installed.php | File has been modified |  
vendor/shopware/storefront/Framework/Routing/StorefrontSubscriber.php | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/layout/navigation/offcanvas/active-item-link.html.twig | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/layout/navigation/offcanvas/back-link.html.twig | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/layout/navigation/offcanvas/categories.html.twig | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/layout/navigation/offcanvas/item-link.html.twig | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/layout/navigation/offcanvas/show-active-link.html.twig | File has been modified |  
vendor/shopware/storefront/Resources/views/storefront/utilities/icon.html.twig | File has been modified |  
vendor/shopware/storefront/Test/Framework/Twig/Extension/IconCacheTwigFilterTest.php

</div></div>`

### Expected behaviour

Can you check please. I don't think it should be like this.

### Steps to Reproduce?

- PHP version 8.0.20
- Shopware version 6.4.16.0
- FroshTools version 0.2.7
- shopware/elasticsearch removed via composer

**Comment by getnatalia** [comment]
I checked today again and there is no manipulated files in the list anymore. So this issue can be closed. Sorry for the inconvenience.

**Comment by shyim** [comment]
all good I have fixed it :joy:

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/api-doc/commit/1072652b5daac99aa5da72a588a318c4904891d6

should hopefully fix it for future. You are soo fast updating :sweat_smile:
