### ISSUE TITLE
Please don't show the tab "Elasticsearch Manager", if elastic search is not enabled

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshTools#131]
### Please describe the feature you would like to see implemented.

 It would be great if the tab "Elasticsearch Manager" is not displayed at all, if elastic search is not enabled. Is it possible?

**Comment by getnatalia** [comment]
Hey Soner, many thanks for the quick implementation. When will the next version with these changes be released?

**Comment by shyim** [comment]
done
