### ISSUE TITLE
Cache tab: Values for free/used space are incorrect

### ISSUE THREAD

**Issue by pogster** [FriendsOfShopware/FroshTools#147]
### PHP Version

8.1.11

### Shopware Version

6.4.16.1

### Actual behaviour

The cache tab has columns with free and used space. The values in these columns do not looks correct.
![image](https://user-images.githubusercontent.com/7595296/197485869-d6970e62-fddf-461a-bca7-b7dec5b85ea2.png)

### Expected behaviour

The values are correct and human-readable.

### Steps to Reproduce?

Open the cache tab.

**Comment by shyim** [comment]
I cannot reproduce this at the latest version anymore
