### ISSUE TITLE
Show paypload of a scheduled task

### ISSUE THREAD

**Issue by tpierschel** [FriendsOfShopware/FroshTools#152]
### Please describe the feature you would like to see implemented.

Dont know if its possible, but it would be very cool if the paypload of a task could be display in a modal.

![image](https://user-images.githubusercontent.com/2543864/200559088-15c799e7-f0cc-46eb-ae9e-a7c721c7f479.png)

**Comment by shyim** [comment]
Queues by design does not allow showing the content. The only way could be to "consume" it and unserialize it, but that could break the message. I don't see a clean way to implement such stuff
