### ISSUE TITLE
Display Node & Composer Version

### ISSUE THREAD

**Issue by tpierschel** [FriendsOfShopware/FroshTools#153]
### Please describe the feature you would like to see implemented.

In some cases would be cool to see the used composer , node / npm version.

**Comment by tinect** [comment]
Do you mean announced bins by PATHs?
There might be some binaries used on system instead of registered PATHs. 🤔

Shopware might ship composer-bin within it's bin-folder.

I'd recommend you to set custom HealthChecker on your shops.

**Comment by shyim** [comment]
Hey,

On professional deployment there should be no composer / node on the system. So I don't see that we should add it here :)
