### ISSUE TITLE
Queue Manager - No queue list by disabling increment storage

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshTools#157]
### Question

PHP 
8.0.20

Shopware version 
6.4.16.1

froshtools version
0.2.12

If the usage of the increment storage is disabled with config/packages/shopware.yml file and following content

shopware:
    increment:
        user_activity:
          type: 'array'

        message_queue:
          type: 'array'

The queue overview disappears in queue manager. 

Is there a way to display the data anyway or is it no longer possible to read out the data with this deactivation?

**Comment by shyim** [comment]
It uses the same data. So it's "okay" that it is empty.

You should use for your queue services like rabbitmq there you have a better dashboard over the queue
