### ISSUE TITLE
Add shopmon role

### ISSUE THREAD

**Issue by PheysX** [FriendsOfShopware/FroshTools#158]
### Please describe the feature you would like to see implemented.

Add shopmon role to shopware and add needed permissions to setup shopmon faster.

https://github.com/FriendsOfShopware/shopmon/blob/main/app/manifest.xml#L18

**Comment by shyim** [comment]
Thats a really cool idea 😅

**Comment by PheysX** [comment]
Sure. After Christmas 🎄

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/FroshTools/pull/251#issuecomment-1961808884
