### ISSUE TITLE
Persistant database in gitpod

### ISSUE THREAD

**Issue by b83s** [FriendsOfShopware/FroshTools#159]
### Please describe the feature you would like to see implemented.

Adding this folder option to the docker init. It stores the MySQL database to the gitpod workspace folder and because it resides in the workspace folder it is persistent.

docker run --restart always -d --name=mysql -v /workspace/mysql:/var/lib/mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8

**Comment by shyim** [comment]
feel free to make a PR

**Comment by shyim** [comment]
Addopted it https://github.com/FriendsOfShopware/FroshTools/commit/b618937ead68fd46e024efa9edb7fb22d7581d4d

**Comment by b83s** [comment]
Next time will do it by PR
