### ISSUE TITLE
Task Checker doesnot take Timezone into consideration?

### ISSUE THREAD

**Issue by Schrank** [FriendsOfShopware/FroshTools#162]
### Actual behaviour

TaskHandler is complaining, that the tasks are not properly run:
![image](https://user-images.githubusercontent.com/379680/210380375-a7cdab14-2e2a-4e7b-8487-5ef1cab9e56a.png)

But the tasks are well on time (Screen from 15:45, Berlin time UTC+1)
![image](https://user-images.githubusercontent.com/379680/210380584-3216c22a-af20-4527-ae44-03c121996030.png)

### Expected behaviour

I expect, that the code in 
https://github.com/FriendsOfShopware/FroshTools/blob/80b3f4e43b0413d579784d0a6369829855f78ddf/src/Components/Health/Checker/HealthChecker/TaskChecker.php#L34-L43

doesn't work well with timezones? But that's only a guess. Didn't investigate it.

### Steps to Reproduce?

- Configure PHP to use Europe/Berlin
- Run `console scheduled-task:run -vv --time-limit=285 --memory-limit=2G` every 5min
- Check the warning

**Comment by shyim** [comment]
your php never uses europe/berlin it's always hard-code to UTC.
https://github.com/shopware/platform/blob/trunk/src/Core/Kernel.php#L76

**Comment by Schrank** [comment]
Thanks! 🤔  Then I have no clue what happens.

**Comment by nfech01** [comment]
I tried to debug it, as I have experience the same problem. I am pretty sure it has to do something with the timezone as changing
`$date->modify(sprintf('-%d minutes', $minutes));`
to
`$date->modify('-1 hour');`
will work again (Setting it to -59minutes will fail though).
However, the dates are all in UTC as far as I can say. I checked the date that is used for the filter as well the result of ->getNextExecutionTime() for all tasks. I don't see why the repository does return all tasks.
Next step would be to check the actual SQL.

**Comment by hummer2k** [comment]
Looks like it has something to do with the [MySQL >= 8.0.26 time zone settings.](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_system_time_zone)

On my local machine it's set to "UTC" and working fine. 
However on the server it is set to "CET" resulting in the mentioned issue. 

Temporarily setting the [time_zone variable](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_time_zone)  to '+00:00' fixed it for me.
But I am not sure if this will break anything else.
