### ISSUE TITLE
It does not work with our current version. The administration module is not showing 

### ISSUE THREAD

**Issue by Selver-nt** [FriendsOfShopware/FroshTools#165]
### Shopware Version

6.4.18.0

### Actual behaviour

It does not work with our current version. The administration module is not showing 

### Expected behaviour

/

### Steps to Reproduce?

/

**Comment by shyim** [comment]
How did you installed it?

**Comment by Selver-nt** [comment]
@shyim just uploaded the plugin to custom/plugins
Installed "jawira/plantuml-encoding": "~1.1.0" in the root composer.json file
and executed bin/console plugin:install --activate FroshTools

**Comment by shyim** [comment]
Just download it from Shopware Store it's free and it will just work

**Comment by Selver-nt** [comment]
@shyim we use Shopware developer version, in previus version and projects, it worked too
But with this requirement not anymore: jawira/plantuml-encoding

old plugin: `  "require": {
        "shopware/core": "~6.4.7"
    },`

new plugin:
`"require": {
    "shopware/core": "~6.4.11",
    "jawira/plantuml-encoding": "~1.1.0"
  },`

**Comment by shyim** [comment]
If you use a release tag the administration failed are committed and should just work. 

When you want to install from Github just use the Zip provided in the releases https://github.com/FriendsOfShopware/FroshTools/tree/0.2.13/src/Resources/public/administration/css

When you want to use composer, just require "frosh/tools" directly in the root `composer.json`.

**Comment by shyim** [comment]
Planuml is really simple let's just inline that code to this plugin, so we can drop it again https://github.com/jawira/plantuml-encoding/blob/master/src/plantuml_functions.php

**Comment by shyim** [comment]
I have removed planuml again as library. The compiled admin files are present in tag or release zip
https://github.com/FriendsOfShopware/FroshTools/commit/a2bdf73c41ac7080fc4aadb92694d706e73b1bbc
