### ISSUE TITLE
Task - product_download.media.cleanup failed

### ISSUE THREAD

**Issue by gstesan** [FriendsOfShopware/FroshTools#176]
### Question

Hi, 
do you have any idea why this failure in Shopware 6.4.20.0 > Administration > Tools - "Scheduled Task" will be shown?
Thanks for a hint! Greetings from Munich.

The request was: 
POST /api/_action/frosh-tools/scheduled-task/6bd8431a37b54bf5ba535b067da688a5 HTTP/1.1
The response is:
{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Call to a member function getConfiguration() on null"}]}
HTTP/1.1 500 Internal Server Error

**Comment by shyim** [comment]
This sounds to me like an general issue with that task. Could you create a issue in the issue tracker?
