### ISSUE TITLE
product_download.media.cleanup failed

### ISSUE THREAD

**Issue by gstesan** [FriendsOfShopware/FroshTools#177]
### PHP Version

8.1.16

### Shopware Version

6.4.20.0

### Actual behaviour

The automatic (and manual) trigger in Shopware 6.4.20.0 > Administration > Tools - "Scheduled Task" for "product_download.media.cleanup" fails. More details visible in Chrome Dev-Tools - specially if you trigger the task manually.

Response:
https://www.xxx.de/api/_action/frosh-tools/scheduled-task/6bd8431a37b54bf5ba535b067da688a5
{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Call to a member function getConfiguration() on null"}]}

Request:
POST /api/_action/frosh-tools/scheduled-task/6bd8431a37b54bf5ba535b067da688a5 HTTP/1.1
Accept: application/vnd.api+json

Response:
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Tue, 07 Mar 2023 11:24:21 GMT
Content-Type: application/json
Transfer-Encoding: chunked

### Expected behaviour

No error for that task.

### Steps to Reproduce?

Written in actual behavior.

**Comment by shyim** [comment]
Hey,

that is nothing related to FroshTools. It sounds like a general Shopware issue with that scheduled task. Can you create a issue there? 
https://issues.shopware.com/
