### ISSUE TITLE
Theme compile not working

### ISSUE THREAD

**Issue by andydandy80** [FriendsOfShopware/FroshTools#178]
### Question

The "Theme compile"-Button in tab "cache" is not working. The message is "theme compiled succesful", but i cannot see my css changes. It only works on console with "php bin/console theme:compile".

**Comment by shyim** [comment]
6.4 or 6.5?

**Comment by andydandy80** [comment]
Sorry, Version 6.4.20.0

**Comment by shyim** [comment]
I tried on 6.4 and 6.5, and I can't reproduce the problem. We don't do something special, we just reassign the current theme to the sales channel to force the recompile.
