### ISSUE TITLE
PCRE-Jit is not active

### ISSUE THREAD

**Issue by VonZubinski** [FriendsOfShopware/FroshTools#181]
### PHP Version

8.1.16

### Shopware Version

6.4.20

### Actual behaviour

The System-Status is showing that **PCRE-Jit** is not active

<img width="599" alt="Screenshot 2023-03-30 at 18 58 58" src="https://user-images.githubusercontent.com/63931403/228895384-cd6d7779-e7df-4ce3-888e-e4d692166501.png">

### Expected behaviour

We checked with our hosting provider and he told us, that it's definitely enabled.
Expected behaviour would be, to show PCRE-Jit as active.

<img width="988" alt="Screenshot 2023-03-30 at 19 00 56" src="https://user-images.githubusercontent.com/63931403/228895993-a7e564e7-4493-4709-9d26-4c414c87f8c1.png">

### Steps to Reproduce?

To reproduce, go into **Settings > Extensions > Tools > System-Status** and Check for the PCRE-Jit status

**Comment by shyim** [comment]
It is not enabled. You see `pcre.jit` is 0

**Comment by VonZubinski** [comment]
@shyim So JIT Support enabled alone, doesn't mean it's active? Should `pcre.jit` show a specific value or just 1 ?

**Comment by shyim** [comment]
I will close this then :) Good luck with your hoster
