### ISSUE TITLE
Internal Server Error 500 during update to 0.2.16

### ISSUE THREAD

**Issue by LK-Webservices** [FriendsOfShopware/FroshTools#186]
### PHP Version

8.1.9

### Shopware Version

6.4.20.1

### Actual behaviour

After clicking on update in the backend the website gives back internal server error 500 with the following error in the error.log:

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Symfony\\Component\\DependencyInjection\\Exception\\RuntimeException: You have requested a non-existent parameter "frosh_tools.elasticsearch.product_fields". Did you mean this: "frosh_tools.elasticsearch.enabled"? in /var/www/vhosts/***/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54\nStack trace:\n#0 /var/www/vhosts/***/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\\Component\\DependencyInjection\\Compiler\\DefinitionErrorExceptionPass->processValue(Object(Symfony\\Component\\DependencyInjection\\Definition), true)\n#1 /var/www/vhosts/***/vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\\Component\\DependencyInjection\\Compiler\\AbstractRecursivePass->processValue(Array, true)\n#2 ***.'`

### Expected behaviour

Update should finish successfully.

### Steps to Reproduce?

Triggered the update in the backend.

**Comment by shyim** [comment]
Just released a new update. Can you show if that works?

**Comment by LK-Webservices** [comment]
Update was successful now. Thank you.
