### ISSUE TITLE
Getting CRITICAL Errors all over Frosh/Tools/

### ISSUE THREAD

**Issue by mmarsching** [FriendsOfShopware/FroshTools#194]
### PHP Version

8.1

### Shopware Version

6.4.20.1

### Actual behaviour

Trying to see the "System-Status"-page I get a loading icon for forever...

The Log viewer shows the follwing messages in the prod-*.log:

Uncaught PHP Exception TypeError: "Frosh\Tools\Components\Health\Checker\HealthChecker\TaskChecker::__construct(): Argument #1 ($scheduledTaskRepository) must be of type Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface, Doctrine\DBAL\Connection given, called in /SHOPWARE_6/var/cache/prod_hca75b4bfb7fc26b0820c4a697f3f670c/Container6Idivvl/Shopware_Core_KernelProdContainer.php on line 28715" at /SHOPWARE_6/custom/plugins/FroshTools/src/Components/Health/Checker/HealthChecker/TaskChecker.php line 24 {"exception":"[object] (TypeError(code: 0): Frosh\\Tools\\Components\\Health\\Checker\\HealthChecker\\TaskChecker::__construct(): Argument #1 ($scheduledTaskRepository) must be of type Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepositoryInterface, Doctrine\\DBAL\\Connection given, called in /SHOPWARE_6/var/cache/prod_hca75b4bfb7fc26b0820c4a697f3f670c/Container6Idivvl/Shopware_Core_KernelProdContainer.php on line 28715 at /SHOPWARE_6/custom/plugins/FroshTools/src/Components/Health/Checker/HealthChecker/TaskChecker.php:24)"} []

and

Uncaught Error: Frosh\Tools\Components\Health\Checker\HealthChecker\TaskChecker::__construct(): Argument #1 ($scheduledTaskRepository) must be of type Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface, Doctrine\DBAL\Connection given, called in /SHOPWARE_6/var/cache/prod_hca75b4bfb7fc26b0820c4a697f3f670c/Container6Idivvl/Shopware_Core_KernelProdContainer.php on line 28715 {"exception":"[object] (TypeError(code: 0): Frosh\\Tools\\Components\\Health\\Checker\\HealthChecker\\TaskChecker::__construct(): Argument #1 ($scheduledTaskRepository) must be of type Shopware\\Core\\Framework\\DataAbstractionLayer\\EntityRepositoryInterface, Doctrine\\DBAL\\Connection given, called in /SHOPWARE_6/var/cache/prod_hca75b4bfb7fc26b0820c4a697f3f670c/Container6Idivvl/Shopware_Core_KernelProdContainer.php on line 28715 at /SHOPWARE_6/custom/plugins/FroshTools/src/Components/Health/Checker/HealthChecker/TaskChecker.php:24)"} []

### Expected behaviour

No error ;)

### Steps to Reproduce?

Loading "System-Status"

**Comment by shyim** [comment]
looks like you have the wrong plugin version. can you check for an update?

**Comment by tinect** [comment]
@mmarsching Did you clear the cache? Otherwise, it looks like you have mixed old code. The error indicates code from version 0.2 or lower.

**Comment by mohamedation** [comment]
i am facing the same issue as @tbpoetke 

any further insights about the issue? or what could be the reason?
