### ISSUE TITLE
Error 500: after clearing the cache, the file proxy-classes.php takes a very long time to be generated 

### ISSUE THREAD

**Issue by lempa** [FriendsOfShopware/FroshTools#213]
### PHP Version

8.1

### Shopware Version

6.4.20.2

### Actual behaviour

After clearing the cache, the cache is rebuilt and on the first hit I get an error 500 with this error message:

```php
Warning: fileperms(): stat failed for /var/cache/prod_h40f9912f8090a2e172a415c87693344d/ContainerWfZmin9/proxy-classes.php
``` 

The file does no exists and after few seconds or couple of reloads the file is generated and everything works again. 

After deactivating frosh tools it works as expected

### Expected behaviour

The file is present at the first hit and the cache will be rebuilt without error 500.

### Steps to Reproduce?

Hard to say. 

It is working on the same server on production environment with the same settings. 
On another staging environment it is not working. 

e are using the latest 6.4 compatible frosh tools version

**Comment by tinect** [comment]
That sounds a lot like opcache is the trigger.

See warning for `opcache.enable_file_override`: https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks#php-config-tweaks
