### ISSUE TITLE
after updating to shopware 6.5.3.2  the plugin "tools" not working

### ISSUE THREAD

**Issue by PV4Tom** [FriendsOfShopware/FroshTools#214]
### Shopware Version

6.5.3.2

### Actual behaviour

cannot activate.
getting this note

Internal Server Error 
Attempted to load class "TaskLoggingMiddlewareCompilerPass" from namespace "Frosh\Tools\Components\Messenger". Did you forget a "use" statement for another namespace?

was working with preliminary shopware version.

### Expected behaviour

can activate it

### Steps to Reproduce?

just activating the plugin after update of shopware and your plugin, now  it shows this notice and goes back to inactive.

**Comment by shyim** [comment]
did you update maybe from cli or from the admin?

**Comment by PV4Tom** [comment]
from admin backend

**Comment by tinect** [comment]
Would anyone please send me via PM in Slack SSH access to the issued environment?

**Comment by PV4Tom** [comment]
seems the last updates solved the problem
