### ISSUE TITLE
php.CRITICAL: Uncaught Error: Class "Redis" not found

### ISSUE THREAD

**Issue by swinde** [FriendsOfShopware/FroshTools#217]
### PHP Version

8.1.2

### Shopware Version

6.5.4.1

### Actual behaviour

Hello, I have set up the CLI workers as indicated in the links at help.creoline.com.

https://help.creoline.com/doc/message-queue-with-redis-configure-WTCVYijsCT
https://help.creoline.com/doc/shopware-6-background-queue-worker-user-rechte-tE5hm37gc6

If Redis is activated there is the following error message in the log:
`php.CRITICAL: Uncaught Error: Class 'Redis' not found {'exception':'[object] (Error(code: 0): Class 'Redis' not found at /srv/www/dev-shopware/public /sw6/vendor/symfony/redis-messenger/Transport/Connection.php:45)'} []
[2023-08-26T13:40:56.312648+00:00] request.CRITICAL: Uncaught PHP Exception SymfonyComponentErrorHandlerErrorClassNotFoundError: 'Attempted to load class 'Redis' from the global namespace. Did you forget a 'use' statement?' at /srv/www/dev-shopware/public/sw6/vendor/symfony/redis-messenger/Transport/Connection.php line 45 {'exception':'[object] (SymfonyComponentErrorHandlerError ClassNotFoundError(code: 0): Attempted to load class 'Redis' from the global namespace.
Did you forget a 'use' statement? at /srv/www/dev-shopware/public/sw6/vendor/ symfony/redis-messenger/Transport/Connection.php:45)'} []
`
With FroshTools (1.2.0) disabled nothing happens so I assume the tool is throwing the error.

### Expected behaviour

FroshTools (1.2.0)

### Steps to Reproduce?

Hello, I have set up the CLI workers as indicated in the links at help.creoline.com.

https://help.creoline.com/doc/message-queue-with-redis-configure-WTCVYijsCT
https://help.creoline.com/doc/shopware-6-background-queue-worker-user-rechte-tE5hm37gc6

**Comment by shyim** [comment]
This has nothing to do with FroshTools. Your PHP does not have Redis extension enabled, contact your hosting provider
