### ISSUE TITLE
config/frosh_tools.yaml throughs error

### ISSUE THREAD

**Issue by riaspirjak** [FriendsOfShopware/FroshTools#219]
### PHP Version

8.2

### Shopware Version

6.5.5.2

### Actual behaviour

I created the config file frosh_tools.yaml for overriding certain system_configs. This works perfectly! 

But if I run the command

`bin/console system:update:prepare`

I get these errors in the terminal: 

In FileLoader.php line 182:
`[Symfony\Component\Config\Exception\LoaderLoadException]                                                                                                                           
  There is no extension able to load the configuration for "frosh_tools" (in "/Users/riaspirjak/Documents/Development/Shopware/kroni-shopware/config/packages/frosh_tools.yaml"). L  
  ooked for namespace "frosh_tools", found ""framework", "twig", "monolog", "debug", "shopware", "elasticsearch", "storefront", "web_profiler"" in /Users/riaspirjak/Documents/Deve  
  lopment/Shopware/kroni-shopware/config/packages/frosh_tools.yaml (which is loaded in resource "/Users/riaspirjak/Documents/Development/Shopware/kroni-shopware/config/packages/fr  
  osh_tools.yaml").`

In YamlFileLoader.php line 808:
`[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                                         
  There is no extension able to load the configuration for "frosh_tools" (in "/Users/riaspirjak/Documents/Development/Shopware/kroni-shopware/config/packages/frosh_tools.yaml"). L  
  ooked for namespace "frosh_tools", found ""framework", "twig", "monolog", "debug", "shopware", "elasticsearch", "storefront", "web_profiler"". `

### Expected behaviour

The command should not through any error. 

### Steps to Reproduce?

Create the config/frosh_tools.yaml file and add some configs there then run the command: 
`bin/console system:update:prepare`

Thanks a lot for checking this out!

**Comment by shyim** [comment]
That's a bug in Shopware which exists since years. :see_no_evil: . that command runs without any plugin loaded :see_no_evil:

**Comment by riaspirjak** [comment]
@shyim okey thanks for the answer :)

**Comment by shyim** [comment]
I will create a ticket and maybe I have time to solve it until next minor 6.5.6.0 :sweat_smile:

**Comment by riaspirjak** [comment]
@shyim thanks, that would be awesome!

**Comment by shyim** [comment]
will be fixed with https://github.com/shopware/shopware/commit/059c2adaf82230c13eda4aed45ad7598cdd4567d
