### ISSUE TITLE
Custom loggers not viewable in the logger viewer

### ISSUE THREAD

**Issue by digitvision** [FriendsOfShopware/FroshTools#22]
### PHP Version

7.4

### Shopware Version

6.4.3.0

### Actual behaviour

I used the logger factory to create a custom logger to log plugin data.
The data is saved within a new .log file but the log viewer doesnt recognize my custom logger key and fails.
<img width="727" alt="Bildschirmfoto 2021-08-13 um 07 43 28" src="https://user-images.githubusercontent.com/41727545/129310726-7fa933f5-74e3-47e8-82b9-885a54b12132.png">
<img width="793" alt="Bildschirmfoto 2021-08-13 um 07 43 34" src="https://user-images.githubusercontent.com/41727545/129310729-16427ece-6f33-4460-b5de-cd19f7c30c22.png">
<img width="328" alt="Bildschirmfoto 2021-08-13 um 07 43 44" src="https://user-images.githubusercontent.com/41727545/129310731-d617fe70-92f9-4f52-96da-3a0672fa70b8.png">
<img width="1194" alt="Bildschirmfoto 2021-08-13 um 07 44 47" src="https://user-images.githubusercontent.com/41727545/129310732-2f58fbd9-41db-4c7d-8116-1b13b03c7830.png">
<img width="828" alt="Bildschirmfoto 2021-08-13 um 07 45 04" src="https://user-images.githubusercontent.com/41727545/129310735-b62e0598-0208-4d40-a6d0-53cdd2c4e8b4.png">

### Expected behaviour

The log is read and shown

### Steps to Reproduce?

Create your own logger and log something.

<service id="dvsn.saved_cart.logger" class="Monolog\Logger">
            <factory service="Shopware\Core\Framework\Log\LoggerFactory" method="createRotating" />
            <argument type="string">my-plugin.logger</argument>
        </service>

**Comment by shyim** [comment]
can you send me one row

**Comment by digitvision** [comment]
here are a few rows:

[2021-08-13T05:49:36.781010+00:00] dvsn.saved-cart.INFO: saved carts found: 1 [] []
[2021-08-13T05:49:36.781071+00:00] dvsn.saved-cart.INFO: removing saved carts [] []
[2021-08-13T05:49:36.810118+00:00] dvsn.saved-cart.INFO: saved carts removed [] []
[2021-08-13T05:49:36.810204+00:00] dvsn.saved-cart.INFO: stopping dvsn.saved-cart.cleanup task [] []
