### ISSUE TITLE
Segmentation fault (core dumped) on plugin activation

### ISSUE THREAD

**Issue by ottschoNaud** [FriendsOfShopware/FroshTools#220]
### PHP Version

8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

### Shopware Version

6.5.2.1

### Actual behaviour

When activating the plugin we get a Segmentation fault (core dumped) error on a specific customer system. On local environment with the same shopware version we dont have any problems with this plugin. It seems there is an issue regarding php setup and php 8 annotations used for symfonys dependency injection. The following annotations cause this error.

#[AutoconfigureTag('frosh_tools.health_checker')]
public function __construct(
#[TaggedIterator('frosh_tools.health_checker')] private readonly iterable $healthCheckers,
#[TaggedIterator('frosh_tools.performance_checker')] private readonly iterable $performanceCheckers
) {
}#[Autowire(service: 'frosh_tools.logger')] private readonly LoggerInterface $froshToolsLogger,

Last one could be another Autowire annotation either, cause its quite difficult to test with this amount of dependencies.

PHP version is

PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

Zend Engine v4.1.2, Copyright (c) Zend Technologies
with Zend OPcache v8.1.2-1ubuntu2.14, Copyright (c), by Zend Technologies

I attached php ini

[phpini.txt](https://github.com/FriendsOfShopware/FroshTools/files/12738198/phpini.txt)

I can also PM staging access if needed.

### Expected behaviour

No segmentation fault and running plugin

### Steps to Reproduce?

Install and activating the plugin

**Comment by tinect** [comment]
@ottschoNaud is this still a problem with a more recent PHP version on your side?

**Comment by ottschoNaud** [comment]
PHP version stayed same, but Shopware is 6.5.6.0 now and it works again.

**Comment by tinect** [comment]
Thank you for the update.
