### ISSUE TITLE
Faulty display in Frosh Tool plugin?

### ISSUE THREAD

**Issue by SebastianNetgrade** [FriendsOfShopware/FroshTools#221]
### Question

Hello all,

I'm not reporting this directly as a bug, but as a support question, as we're not sure how the following comes about:

According to our developers we get information in the queue messenger of your plugin, that does not match the information they read directly from the database. 

I don't know if this matches this, but also the Shopware notifications show indexing processes that are actually not running, maybe this helps in connection with the Frosh info. 

I have attached a few screenshots for better understanding.

Thanks a lot for the help

Greetings
Sebastian

![console](https://github.com/FriendsOfShopware/FroshTools/assets/62643978/4dfafb22-baeb-427d-8d62-8debb819f1ac)
![sw-admin-frosh-tools-and-console](https://github.com/FriendsOfShopware/FroshTools/assets/62643978/e173f81e-2356-4798-a660-03030c1f1d2
![sw-admin-notifications](https://github.com/FriendsOfShopware/FroshTools/assets/62643978/9e754976-e247-44d7-b26a-026cb4dbb9b5)
b)

**Comment by SebastianNetgrade** [comment]
sorry, something went wrong with the screenshots. here the failing one:
![sw-admin-frosh-tools-and-console](https://github.com/FriendsOfShopware/FroshTools/assets/62643978/103d2849-af93-40ad-bbc0-f1fbc6e86c1a)

**Comment by SebastianNetgrade** [comment]
We're on Shpoware Version 6.4.16.1 and plugin-version is 0.2.17. Would you recommend updating the plugin, or do you know of any corresponding bugs that may occur in this version in connection with our issue?

**Comment by shyim** [comment]
We just use the existing data in Shopware to display it. so Queue Manager is the same as the notification in Shopware

**Comment by SebastianNetgrade** [comment]
Ok, then I will open a ticket directly at Shopware, thanks.

**Comment by SebastianNetgrade** [comment]
Ok, then I will open a ticket directly at Shopware, thanks.
