### ISSUE TITLE
Feature Request: Enhanced Log Viewer to Support Subdirectories

### ISSUE THREAD

**Issue by amargoShop** [FriendsOfShopware/FroshTools#240]
### Please describe the feature you would like to see implemented.

**Description:**
The current log viewer functionality displays all log files located in the var/log directory. However, certain plugins, such as CleverReach, store their logs in subdirectories. When attempting to select a log file from one of these subdirectories, the log viewer returns an error, stating "file not found."

**Feature Request:**
I propose enhancing the log viewer to support log files stored in subdirectories. This improvement would ensure a seamless experience for users working with plugins that organize logs in subdirectories, such as CleverReach. By accommodating subdirectory structures, the log viewer can provide a comprehensive overview of all log files, improving usability and addressing the "file not found" issue associated with selecting logs from plugins like CleverReach.

**Expected Benefits:**
Improved compatibility with plugins storing logs in subdirectories. Enhanced user experience by eliminating "file not found" errors when selecting logs from specific plugins. Comprehensive log visibility, encompassing both root and subdirectory log files in the log viewer.

**Additional Notes:**
Feel free to reach out if further clarification or details are needed. Thank you for considering this feature request.

**Comment by tinect** [comment]
I'd like to check, if it's worthwhile, the example is just Cleverreach.
Do they use correct monolog or any custom base?

Do you have some example lines and paths for me?

**Comment by shyim** [comment]
They use monologger configs :)

https://github.com/Adyen/adyen-shopware6/blob/develop/src/Resources/config/logger/logger-services.xml#L36-L70
