### ISSUE TITLE
security.json cannot check

### ISSUE THREAD

**Issue by renemennyde** [FriendsOfShopware/FroshTools#248]
### Question

Hello Guys, thanks for the great plugin, i install it in Release 1.3.1 and 1.3.2 with shopware 6.5.8.2 and 3 but all the time i receive "Cannot check security.json from shopware-static-data. This is new since 1.3.1, how i can prevent it?

best regards rene@menny.de
![Uploading Bildschirmfoto 2024-02-08 um 15.58.16.png…]()
de

**Comment by tinect** [comment]
I'll close here due to inactivty.

Please check the PHP config: allow_url_fopen
