### ISSUE TITLE
messenger.transport.scheduler_shopware with unknown size under Queue manager

### ISSUE THREAD

**Issue by birat-ditegra** [FriendsOfShopware/FroshTools#252]
### Shopware Version

6.6 RC3

### Plugin Version

2.1.2

### Actual behaviour

If we open the Queue manager in the admin area, there is a listing for messenger.transport.scheduler_shopware with an unknown size 
![image](https://github.com/FriendsOfShopware/FroshTools/assets/135617401/88896642-8c2d-4621-af3d-20bfc795b672)

### Expected behaviour

messenger.transport.scheduler_shopware should be ignored

### Steps to Reproduce?

On shop with 6.6 RC3 installed, open the queue manager inside Tools plugin

**Comment by hw-dwalter** [comment]
any news on this?

**Comment by commanderape** [comment]
i have the same issue as well. SW 6.6.6.0

**Comment by pf-iservice** [comment]
the same issue for me in 6.6.5.1

**Comment by shyim** [comment]
You can ignore it

**Comment by thesec** [comment]
If it is not required and can be ignored - remove it instead of wasting people's time with it.

**Comment by tinect** [comment]
> If it is not required and can be ignored - remove it instead of wasting people's time with it.

our tone is inappropriate. If you feel it's necessary to speak to developers like this when they're providing features for free, perhaps you should consider uninstalling the plugin.

**Comment by thesec** [comment]
You can consider the given feedback or ignore it. Simply getting personal ignorant as well as arrogant.

**Comment by tinect** [comment]
> You can consider the given feedback or ignore it. Simply getting personal is just ignorant as well as arrogant.

I tried to find you in community slack. :-(
I just wanted to discuss, why I couldn't find any feedback, just an unfriendly instruction.  But for the moment, it is okay for me, while we need to save time.
