### ISSUE TITLE
Scheduled tasks

### ISSUE THREAD

**Issue by JNDUFOUR** [FriendsOfShopware/FroshTools#253]
### Question

I am reaching out today because I have encountered an issue with my Shopware 6.5.8 installation. I have noticed a persistent error indicating "Scheduled tasks overdue," with a warning specifying a delay of 76 minutes, whereas the maximum acceptable delay is 10 minutes.

However, I have added the following cron job to the server to run every 3 minutes:

javascript

/bin/console messenger:consume async --time-limit=30 --memory-limit=128M >/dev/null 2>&1

<img width="457" alt="Capture d’écran 2024-03-12 à 20 45 02" src="https://github.com/FriendsOfShopware/FroshTools/assets/105230067/ea31980a-ab2e-49f1-84ff-0b444c943b7b">
<img width="457" alt="Capture d’écran 2024-03-12 à 20 45 02" src="https://github.com/FriendsOfShopware/FroshTools/assets/105230067/b3c42c84-155e-486f-8441-bf29b2188c9b">

**Comment by jankal** [comment]
Hey @JNDUFOUR
Your command does not run scheduled tasks.

To run scheduled tasks periodically, refere to the the shopware docs - https://developer.shopware.com/docs/guides/plugins/plugins/plugin-fundamentals/add-scheduled-task.html#executing-the-scheduled-task

```
$ bin/console scheduled-task:run
```

**Comment by tinect** [comment]
We'll close here.
