### ISSUE TITLE
Open Queues Warning

### ISSUE THREAD

**Issue by duke2421** [FriendsOfShopware/FroshTools#255]
### PHP Version

8.2.5

### Shopware Version

6.6.1.1

### Plugin Version

2.1.2

### Actual behaviour

System-Status shows, that the Open Queues is not running, but is is. We have a cron job that runs it every 5 Minutes. But even if I run the comand directly, thet System-Status does not change.
![SW6-Tools](https://github.com/FriendsOfShopware/FroshTools/assets/9901356/4b2ba1cb-3138-436c-af04-445a84bd83c4)

### Expected behaviour

Open Queues should show, that the script is working.

### Steps to Reproduce?

Update to latest Version (2.1.2).

**Comment by Soho-Jo** [comment]
Did you  adapt the command for the cronjob? 

_php bin/console messenger:consume async_

becomes

_php bin/console messenger:consume async low_priority_ 


https://github.com/shopware/shopware/blob/v6.6.1.2/UPGRADE-6.6.md

**Comment by duke2421** [comment]
@Soho-Jo  Thank you for your reply. No, I didn't, somehow I overlooked that. 
However, this does not seem to have solved the problem. The plugin now displays ‘unknown’ instead of the last time the script ran.

**Comment by Orgoth** [comment]
In Shopware 6.6.3.0 with Tools 2.1.2, same problem.
Regardless of the cronjob "-vvv" returning success "was handled successfully (acknowledging to transport)." it still hanging in queued and time warning.

```
09:49:44 INFO      [messenger] Received message Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask
[
  "class" => "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask"
]
09:49:44 INFO      [messenger] Message Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask handled by Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTaskHandler::__invoke
[
  "class" => "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask",
  "handler" => "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTaskHandler::__invoke"
]
09:49:44 INFO      [messenger] Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask was handled successfully (acknowledging to transport).
[
  "class" => "Shopware\Core\Content\ProductExport\ScheduledTask\ProductExportGenerateTask"
]
```

**Comment by tinect** [comment]
"unknown" is correct and it's just a info.
