### ISSUE TITLE
MariaDB version is not recognized under Performance

### ISSUE THREAD

**Issue by abwerk** [FriendsOfShopware/FroshTools#256]
### Shopware Version

6.5

### Plugin Version

1.3.3

### Actual behaviour

MariaDB version is not recognized correctly under Performance.
The version is recognized correctly under System Status.

MariaDB is officially recommended by Shopware:
https://docs.shopware.com/en/shopware-6-en/first-steps/system-requirements#environment

![01](https://github.com/FriendsOfShopware/FroshTools/assets/75976744/a069e61a-52e4-4298-8fc0-a74f259c7ab7)

![02](https://github.com/FriendsOfShopware/FroshTools/assets/75976744/0c20a16f-ea5b-48a4-b3d5-c262be3c1f9f)

### Expected behaviour

Recognize MariaDB version and do not issue an error/warning.

### Steps to Reproduce?

Nothing.

**Comment by shyim** [comment]
see https://developer.shopware.com/docs/guides/hosting/performance/performance-tweaks.html#mysql-instead-of-mariadb

**Comment by abwerk** [comment]
Then a warning instead of an error.
And only the MariaDB version, as with System Status.
