### ISSUE TITLE
dependency on a non-existent service "frosh_tools.logger

### ISSUE THREAD

**Issue by Soho-Jo** [FriendsOfShopware/FroshTools#259]
### PHP Version

8.2

### Shopware Version

6.2.2.0

### Plugin Version

2.1.2

### Actual behaviour

After we updated Shopware to 6.6.2.0 the deactivated Tools Plugin was updated to 2.1.2. 
When trying to activate the following message appears:
_Internal Server Error
The service "Frosh\Tools\Controller\ShopwareFilesController" has a dependency on a non-existent service "frosh_tools.logger"._
![Unbenannt-1](https://github.com/FriendsOfShopware/FroshTools/assets/171272866/ce038fbe-553f-475b-b9a8-18a923399575)

### Expected behaviour

We did the same in our similar Staging-System, where it worked without problems.

### Steps to Reproduce?

updated to 2.1.2

**Comment by shyim** [comment]
Can you try to clear the cache + clear the PHP opcache ?

**Comment by Soho-Jo** [comment]
As we run on shared-hosting, clearing the opcache is not possible (for security reasons, all-inkl says).
However, deactivating the Opcache via user.in (opcache.enable = 0) was the way.
We activated the tool and then set the opcache to active again. Now it works.
Many thanks for the quick help!

**Comment by Soho-Jo** [comment]
A brief update as it did no work as proper as I first said.
Yes, Frosch Tools was running, but the Performance recommendations weren't loading.
After contacting our hoster, they cleared the opcache manually. 
Now it seems to be OK, 🤞
