### ISSUE TITLE
The service "Frosh\Tools\Controller\ShopwareFilesController" has a dependency on a non-existent service "frosh_tools.logger".

### ISSUE THREAD

**Issue by AndrMER** [FriendsOfShopware/FroshTools#261]
### Question

After Update Showare to 6.6.3.0
I get follow error if i want install/upgrade Frosch tools
Any Idea?

Internal Server Error

The service "Frosh\Tools\Controller\ShopwareFilesController" has a dependency on a non-existent service "frosh_tools.logger".

**Comment by AndrMER** [comment]
If i want install/upgrade Frosch "Warenkorb Teilen"
I get follow error

all other plugin's and Shop run fine...

Internal Server Error

Cannot autowire service "Frosh\ShareBasket\Services\ShareBasketService": argument "$shareBasketRepository" of method "__construct()" references class "Shopware\Core\Framework\DataAbstractionLayer\EntityRepository" but no such service exists. Did you mean to target one of "log_entry.repository", "acl_role.repository", "acl_user_role.repository", "app.repository",

**Comment by tinect** [comment]
Sounds like opcache issues.

**Comment by tinect** [comment]
closed due to inactivity
