### ISSUE TITLE
permission denied after update shopware 6.6.4.0

### ISSUE THREAD

**Issue by chrimaluxe** [FriendsOfShopware/FroshTools#262]
### PHP Version

8.3

### Shopware Version

6.6.4.0

### Plugin Version

2.1.2

### Actual behaviour

After updating shopware to 6.6.4.0, i get an error as:

Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessStartFailedException: "The command "'du' '-s' '/..../staging1/var/cache/dev_hf58137c4d7d70c1d186f7d854e39f295'" failed. Working directory: /...../staging1/public Error: proc_open(): posix_spawn() failed: Permission denied" at Process.php line 371 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessStartFailedException(code: 0): The command \"'du' '-s' '/..../staging1/var/cache/dev_hf58137c4d7d70c1d186f7d854e39f295'\" failed.\n\nWorking directory: /..../staging1/public\n\nError: proc_open(): posix_spawn() failed: Permission denied at /....../staging1/vendor/symfony/process/Process.php:371)"} []

This is the result:
![cache](https://github.com/FriendsOfShopware/FroshPlatformMailArchive/assets/15171666/f55b3a14-d1ef-4448-bb9d-83e4c6c0f887)

With 6.6.3.1 it works without issues. For me it seems there was a change in the core and calling the function disk usage gets the "permission denied".

### Expected behaviour

Normal usage with function disk usage

### Steps to Reproduce?

Update from shopware 6.6.3.1 to 6.6.4.0

**Comment by tinect** [comment]
Hi @chrimaluxe 

I've transferred your issue to the FroshTools-Repo, while it doesn't match to MailArchive, does it?

It looks like you have some mixed permissions within the cache-folder. Could you please remove it manually?

**Comment by chrimaluxe** [comment]
Hi @tinect 

Yes, FroshTools-Repo is correct, sorry.

I have removed the cache folder and after restart, it was created again, but with the same result, permission denied. The main cache folder has 777 rights. But within the folder, there are some additional folders and files with different permissions, Looks like that:

![cache-perm](https://github.com/FriendsOfShopware/FroshTools/assets/15171666/b670c69f-e1e1-4e8a-bb8a-e7ad6588a4f7)

But when i check with a 6.6.3.1 installation, the permissions within the cache folder are the same. But 6.6.3.1 is working, 6.6.4.0 not.

**Comment by chrimaluxe** [comment]
Here is a comment, that i was told by a friend:

Es wurde bei Symfony der Code für Systemaufrufe in letzter Zeit mehrfach überarbeitet, früher wurde keine Exception "geworfen", jetzt schon und im FroshTool wird das nicht abgefangen, was es (inzwischen) eigentlich müsste, sonst passiert genau das, was jetzt passiert.

**Comment by tinect** [comment]
thank you, then please just allow the execution.

**Comment by chrimaluxe** [comment]
I don't know how I could do that. Even if I give the entire folder 777 rights, it doesn't work. That's all I can do here. The problem may be due to different users calling the individual scripts. However, only a user who has his own server can check this. Anyone who uses a hoster has no influence here and can only set the user rights to 777.

Perfect, when you check this. Thanks!

**Comment by tinect** [comment]
If files are generated with the wrong user, there might be additional issues with your installation beyond the processes being used. You should address this in your setup. Catching process usage won't fix permission problems, and using 777 is not a solution for anything.

You will understand that we cannot support every configuration of setups with hosting providers.

Therefore, I will close this ticket for now. Please have someone with DevOps and possibly Symfony experience review your setup and especially the hosting provider.
