### ISSUE TITLE
Log viewer does not work with Shopware 6.6

### ISSUE THREAD

**Issue by mbranzcominto** [FriendsOfShopware/FroshTools#263]
### PHP Version

8.3.9

### Shopware Version

6.6.3.1, 6.6.4.1

### Plugin Version

2.1.2

### Actual behaviour

The Log viewer find all rows, but the all fields of the lines delivered by the API are null:

```
{
        "message": null,
        "channel": null,
        "date": null,
        "level": null
},
```

![image](https://github.com/user-attachments/assets/6d9e94dd-8fb0-45dc-97a7-b5f8e640ed17)

### Expected behaviour

That the Log viewer shows the logs.

### Steps to Reproduce?

1. Use the https://github.com/shopware/docker as base docker image
2. Install the Tool's plugin from the Shopware Store via composer.json
3. Start the container
4. Go to the Log viewer and see that the logs are not shown correctly

**Comment by shyim** [comment]
shopware/docker does not use files for logging instead pushing it to STDOUT so the container runtime can grab the logs. So this is normal

**Comment by mbranzcominto** [comment]
Yes, the logs are shown in the STDOUT, but the log files are generated and have content.
Also, the number of lines of the file are correctly delivered, but the LogController cannot read/decode them, maybe because it is a JSON and not a simple log?

**Comment by shyim** [comment]
yes because they are json. but they should not be generated at all 🤔
