### ISSUE TITLE
opcache.enable_file_override=1 incorreclty marked as warning

### ISSUE THREAD

**Issue by carstenjaksch** [FriendsOfShopware/FroshTools#264]
### PHP Version

8.3

### Shopware Version

6.5.8.6

### Plugin Version

1.3.3

### Actual behaviour

The plugin incorrectly marks `opcache.enable_file_override=1` as warning.

<img width="1267" alt="Bildschirm­foto 2024-07-18 um 09 47 01" src="https://github.com/user-attachments/assets/88e8f3af-0b60-47a4-9299-8d8a9cd292a8">

### Expected behaviour

`opcache.enable_file_override=1` should be treated as the recommended value `on`.

### Steps to Reproduce?

Set `opcache.enable_file_override=1` and go to shop status.

We are currently unable to update to the latest version, but I don't see any related fixes in the changelog.

**Comment by schneider-felix** [comment]
This issue will be resolved in the next release. Thank you for bringing this up.
