### ISSUE TITLE
Cache tab is running into an endless queue

### ISSUE THREAD

**Issue by crs-computer** [FriendsOfShopware/FroshTools#266]
### PHP Version

8.3.8

### Shopware Version

6.6.4.1

### Plugin Version

2.1.3

### Actual behaviour

Caching function / tab is in an endless queue. Please give us a hint to fix it.
Please find below screenshot

![Screenshot_2](https://github.com/user-attachments/assets/68548bb0-c60b-466e-b47d-9374564dfbc3)

### Expected behaviour

Normaly (from other shops) you will find a list below instead of the queue.

### Steps to Reproduce?

No idea, it happend from one day to the next.

**Comment by shyim** [comment]
any errors in network tab in chrome?

**Comment by crs-computer** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/0e1277a9-cf07-472f-b23f-7ac4ba1b26e1)
