### ISSUE TITLE
Verbindung funktioniert nicht

### ISSUE THREAD

**Issue by web-grips** [FriendsOfShopware/FroshTools#280]
### Question

Hallo,
in Windows bekomme ich den Fehler "Der eingegebene Ordner ist ungültig...."
Wenn ich die URL im Browser aufrufe und die Logindaten eingebe bekomme ich einen Fehler "Error 1101 ... Worker threw exception"

Der Shop hat einen htaccess-Schutz, den ich aber auch schon deaktiviert hatte.

Vielen Dank für den Support
Oliver

**Comment by tinect** [comment]
Hallo @web-grips,

hat deine Anfrage vielleicht nichts direkt mit dem Plugin zu tun? Für Supportfragen bist du in Slack oder anderen Kanälen vermutlich besser aufgehoben.
