### ISSUE TITLE
Package is missing from shopware repo

### ISSUE THREAD

**Issue by func0der** [FriendsOfShopware/FroshTools#295]
### PHP Version

8.1

### Shopware Version

6.4

### Plugin Version

all

### Actual behaviour

```
./composer.json has been updated
Running composer update store.shopware.com/froshtools
> [ ! -f vendor/autoload.php ] || $PHP_BINARY bin/console system:update:prepare
Run Update preparations
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires store.shopware.com/froshtools, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Composer [require store.shopware.com/froshtools:*] failed, composer command failed: exit status 2. stderr=
```

### Expected behaviour

Package would be installed

### Steps to Reproduce?

1. Run `composer require store.shopware.com/froshtools:*`

**Comment by schneider-felix** [comment]
Thanks for reaching out. Sadly I was not able to reproduce this issue. Please make sure you added the licensed the plugin via store.shopware.com and are using the correct access token.

![Image](https://github.com/user-attachments/assets/5454c21f-babd-48bc-8690-88bbbeffe176)

If you continue to have problems with the installation, please reach out to shopware as we do not have any control over the composer package registry. You can also try installing the plugin using packagist: https://packagist.org/packages/frosh/tools

```bash
composer require frosh/tools
```
