### ISSUE TITLE
md5sums wrong

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/FroshTools#50]
### Actual behaviour

There are files marked false-positive.

https://github.com/FriendsOfShopware/api-doc/commit/d3823332f34967af1fa2e3744f2825bd39514586#diff-093e78f55ca2404d6730628879e060e82349751e597ad60fa389ba8038cad951

Does it look like the updater isn't working properly? Why have old md5sums been changed? 🤔 

### Expected behaviour

There should be correct report.

### Steps to Reproduce?

Install 6.5.4.1, see tab "Shopware file checker" of FroshTools .

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/api-doc/commit/3f1e60eec2ba0421a54c285787e8d854688304fe
