### ISSUE TITLE
Warning: file_get_contents(https://github.com/shopware/platform/blob/v6.4.9.0/src/Administration/Resources/public/static/js/app.js?raw=true)

### ISSUE THREAD

**Issue by vardumper** [FriendsOfShopware/FroshTools#65]
### PHP Version

8.0.16

### Shopware Version

6.4.7.0 - 6.4.9.0

### Actual behaviour

When opening the File Checker, I get a 404 error. The file seems to absent from the repo. 

### Expected behaviour

No error is thrown.

### Steps to Reproduce?

Open File Checker

**Comment by shyim** [comment]
We need to skip that file or look into the many repositories for that
