### ISSUE TITLE
How can I check if Compilation works correct?

### ISSUE THREAD

**Issue by Anis108** [FriendsOfShopware/FroshTools#72]
### Question

Thanks for this plugin :) it supports my wish to have an overview.

I'm unsure how the compilation function works.
When I press the compilation button the effect is in the two boxes "Cache" and "Action" appear loading wheels and the just keep spinning for minutes.

All other sections of the plugin show no indication of errors or other shortcomings
Any suggestions are welcome :)

Shopware 6.4.10.1
Gut | PHP-Version: 8.0.18
Gut | Max-Execution-Time: 900 Sekunden
Gut | Memory-Limit: 512M
Gut | Zend Opcache ist aktiv
Gut | MariaDB-Version: 10.3.34

**Comment by tinect** [comment]
After several seconds there should be similar notifications:
![image](https://user-images.githubusercontent.com/135993/164779392-f52f923f-8ce2-4910-9eef-1b6b558fd210.png)

If you have many saleschannels, many plugins or a slow server this may take some seconds.
If not, please check error-logs.

**Comment by Anis108** [comment]
Thank you tinect for you display & suggestions.
We have a slim installation with maybe three plugins installed.
I assume we need an adjustmend on the server (root server) or something like that.

In the "dev.log" ther is the following:


Zeitpunkt	
Kanal	
Level	
Nachricht
2022-04-25T07:18:26.583936+00:00
php
INFO
User Deprecated: Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Swag\PayPal\OpenApi\OpenApiPathsSubscriber" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Symfony\\Component\\EventDispatcher\\EventSubscriberInterface::getSubscribedEvents()\" might add \"array\" as a native return type declaration in the future. Do the same in implementation \"Swag\\PayPal\\OpenApi\\OpenApiPathsSubscriber\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.579121+00:00
php
INFO
User Deprecated: Method "Symfony\Component\EventDispatcher\EventSubscriberInterface::getSubscribedEvents()" might add "array" as a native return type declaration in the future. Do the same in implementation "Swag\FlowBuilderProfessional\Core\Content\Flow\Subscriber\BusinessEventCollectorSubscriber" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Symfony\\Component\\EventDispatcher\\EventSubscriberInterface::getSubscribedEvents()\" might add \"array\" as a native return type declaration in the future. Do the same in implementation \"Swag\\FlowBuilderProfessional\\Core\\Content\\Flow\\Subscriber\\BusinessEventCollectorSubscriber\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525942+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\StreamInterface::getMetadata()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\StreamInterface::getMetadata()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\Stream\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525140+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::getAttribute()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::getAttribute()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525113+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withParsedBody()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withParsedBody()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525083+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::getParsedBody()" might add "array|object|null" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::getParsedBody()\" might add \"array|object|null\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525047+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withQueryParams()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withQueryParams()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.525005+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withCookieParams()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withCookieParams()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.524870+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withUploadedFiles()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withUploadedFiles()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.521079+00:00
request
INFO
Matched route "api.frosh.tools.logs.file-listing". {"route":"api.frosh.tools.logs.file-listing","route_parameters":{"_route":"api.frosh.tools.logs.file-listing","_controller":"Frosh\\Tools\\Controller\\LogController::getLog"},"request_uri":"https://www.aaaaa.bb/test/public/api/_action/frosh-tools/logs/file?file=dev.log&limit=25&offset=0","method":"GET"} []
2022-04-25T07:18:26.507161+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\StreamInterface::getMetadata()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\StreamInterface::getMetadata()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\Stream\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506352+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::getAttribute()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::getAttribute()\" might add \"mixed\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506319+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withParsedBody()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withParsedBody()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506289+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::getParsedBody()" might add "array|object|null" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::getParsedBody()\" might add \"array|object|null\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506259+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withQueryParams()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withQueryParams()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506224+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withCookieParams()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withCookieParams()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.506172+00:00
php
INFO
User Deprecated: Method "Psr\Http\Message\ServerRequestInterface::withUploadedFiles()" might add "static" as a native return type declaration in the future. Do the same in implementation "Nyholm\Psr7\ServerRequest" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"Psr\\Http\\Message\\ServerRequestInterface::withUploadedFiles()\" might add \"static\" as a native return type declaration in the future. Do the same in implementation \"Nyholm\\Psr7\\ServerRequest\" now to avoid errors or add an explicit @return annotation to suppress this message. at /var/www/vhosts/aaaaa.bb/httpdocs/public/test/vendor/symfony/error-handler/DebugClassLoader.php:325)"} []
2022-04-25T07:18:26.501199+00:00
request
INFO
Matched route "api.notification.message". {"route":"api.notification.message","route_parameters":{"_route":"api.notification.message","_controller":"Shopware\\Administration\\Controller\\NotificationController::fetchNotification"},"request_uri":"https://www.aaaaa.bb/test/public/api/notification/message?limit=5","method":"GET"} []
2022-04-25T07:18:26.429750+00:00
app
INFO
cache-miss: system-config- [] []

**Comment by tinect** [comment]
Which version are you using? Could you please update to the most recent version coming today?

There is no way to hire my service because I can't offer this. :-(

Could you please test with current version?

**Comment by Anis108** [comment]
Thank you for the prompt reply.
This version is up to date. 1.5.0

is it relevant that the 'cache.property_access' is unkown?
starting the compilation function brings also a 500 error under messages upper right in the following screenshot.

![image](https://user-images.githubusercontent.com/5931453/165073411-9ade9da4-80c5-4b9b-830e-712d5e7995b7.png)


The log from this plugin "prod-2022-04-25.log"

2022-04-25T08:49:24.277654+00:00
request
ERROR
Uncaught PHP Exception Shopware\Storefront\Framework\Captcha\Exception\CaptchaInvalidException: "The provided value for captcha "Shopware\Storefront\Framework\Captcha\HoneypotCaptcha" is not valid." at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/shopware/storefront/Framework/Captcha/CaptchaRouteListener.php line 76 {"exception":"[object] (Shopware\\Storefront\\Framework\\Captcha\\Exception\\CaptchaInvalidException(code: 0): The provided value for captcha \"Shopware\\Storefront\\Framework\\Captcha\\HoneypotCaptcha\" is not valid. at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/shopware/storefront/Framework/Captcha/CaptchaRouteListener.php:76)"} []
2022-04-25T07:33:34.167285+00:00
request
ERROR
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache" (from "https://www.platzhalter.usw/admin")" at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\" (from \"https://www.platzhalter.usw/admin\") at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\". at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
2022-04-25T07:33:21.762687+00:00
request
ERROR
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache" (from "https://www.platzhalter.usw/admin")" at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\" (from \"https://www.platzhalter.usw/admin\") at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\". at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []
2022-04-25T07:33:11.984813+00:00
request
ERROR
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache" (from "https://www.platzhalter.usw/admin")" at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php line 135 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST https://www.platzhalter.usw/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\" (from \"https://www.platzhalter.usw/admin\") at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/http-kernel/EventListener/RouterListener.php:135)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/testpublic/api/v%7Bversion%7D/_admin/netzp/staging/cache\". at /var/www/vhosts/platzhalter.usw/httpdocs/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:74)"} []

**Comment by Anis108** [comment]
I'm glad that you clarify the errors listed.
I deinstalled all other plugins.
Left just the ones shopware came with.

Now I realize I posted the "wrong error log" ^^

Here is the one related to this plugin.

25. April 2022, 17:36
TypeError: Cannot read properties of null (reading 'id')
Fehler (400)
{ "component": "Unknown component", "stack": "TypeError: Cannot read properties of null (reading 'id')\n at https://www.platzhalter.usw/bundles/froshtools/administration/js/frosh-tools.js?165088221581396:1:61614\n at u (https://www.platzhalter.usw/bundles/administration/static/js/vendors-node.js?16505635811582962:2:680755)\n at Generator._invoke (https://www.platzhalter.usw/bundles/administration/static/js/vendors-node.js?16505635811582962:2:680543)\n at Generator.next (https://www.platzhalter.usw/bundles/administration/static/js/vendors-node.js?16505635811582962:2:681180)\n at U (https://www.platzhalter.usw/bundles/froshtools/administration/js/frosh-tools.js?165088221581396:1:59066)\n at i (https://www.platzhalter.usw/bundles/froshtools/administration/js/frosh-tools.js?165088221581396:1:59269)", "url": "https://www.platzhalter.usw/admin#/frosh/tools/index/cache" }

**Comment by shyim** [comment]
If you have a staging environment, you can send us also the credentials at `contact@fos.gg`. I guess it's easier to come forward here

**Comment by shyim** [comment]
is fixed with https://github.com/FriendsOfShopware/FroshTools/releases/tag/0.1.7
