### ISSUE TITLE
Error: Call to undefined method Frosh\Tools\Components\Elasticsearch\EsProductDefinition::extendEntities()

### ISSUE THREAD

**Issue by HepGon** [FriendsOfShopware/FroshTools#79]
### PHP Version

8.0.14

### Shopware Version

6.4.10.1

### Actual behaviour

after installing the Tools Plugin from frosh I get the following error in dead_message:
Error
Call to undefined method Frosh\Tools\Components\Elasticsearch\EsProductDefinition::extendEntities()
***/custom/plugins/SwagEnterpriseSearchPlatform/src/Indexing/DocumentProvider.php 55

after running the plugin a few hours there were a few hundreds of this errors in dead_message table, after deactivating the plugin, the messages were delted

### Expected behaviour

no error in dead_message

### Steps to Reproduce?

just installed the plugin and then had a check of the dead_message table in database

**Comment by shyim** [comment]
In the newest version of SwagEnterpriseSearchPlatform, it calls extendDocuments and not extendEntities
