### ISSUE TITLE
Getting compile error when running admin-watch 

### ISSUE THREAD

**Issue by zaifastafa** [FriendsOfShopware/FroshTools#80]
### PHP Version

7.4

### Shopware Version

trunk

### Actual behaviour

    
    ERROR in /var/www/html/custom/plugins/FroshTools/src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-files/index.js
    Module not found: Error: Can't resolve 'diff-match-patch' in '/var/www/html/custom/plugins/FroshTools/src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-files'

### Expected behaviour

Compile successfully

### Steps to Reproduce?

Run administration watch command.

**Comment by shyim** [comment]
run npm install inside the folder where the package.json is

**Comment by Isengo1989** [comment]
@shyim is there a longterm solution for this? 

afaik jq is used to find the packages.json files and install in the vendor folders, no? The manual task is a little cumbersome.

Maybe there is something on the way already in 6.5 ?

**Comment by shyim** [comment]
When jq is installed on the prod templateit should just work

**Comment by Isengo1989** [comment]
I think this is not mentioned in the requirement anywhere

https://github.com/shopware/production#requirements

I thought maybe there is a better way of solving that by a onboard package in major unix systems.

Anyhow, pipeline ran now :laughing: 

![image](https://user-images.githubusercontent.com/8600299/172070844-2c37cf07-ea3a-45c2-9b05-f4900818b0db.png)

**Comment by shyim** [comment]
feel free to contribute. Needs to work with bash + npm and basic unix tools 😅
