### ISSUE TITLE
Cache size unknown with redis (?)

### ISSUE THREAD

**Issue by MarcusRobichon** [FriendsOfShopware/FroshTools#93]
### Question

Since I installed redis on the server I wonder why the Memory size used and free is "unknown". Is this correct, or am I missing something?

![image](https://user-images.githubusercontent.com/45993087/177418788-f5332687-89de-4edb-acbc-ea3004773698.png)

**Comment by shyim** [comment]
are you on the latest version?

**Comment by MarcusRobichon** [comment]
Yes, 0.21


-------- Ursprüngliche Nachricht --------
Von: Shyim ***@***.***>
Datum: 06.07.22 09:41 (GMT+01:00)
An: FriendsOfShopware/FroshTools ***@***.***>
Cc: Marcus Robichon ***@***.***>, Author ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshTools] Cache size unknown with redis (?) (Issue #93)


are you on the latest version?

**Comment by shyim** [comment]
which shopware version?

**Comment by MarcusRobichon** [comment]
6.4.13, but it also was on 6.4.12 unkown


-------- Ursprüngliche Nachricht --------
Von: Shyim ***@***.***>
Datum: 06.07.22 09:48 (GMT+01:00)
An: FriendsOfShopware/FroshTools ***@***.***>
Cc: Marcus Robichon ***@***.***>, Author ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshTools] Cache size unknown with redis (?) (Issue #93)


which shopware version?

**Comment by tinect** [comment]
Hey @MarcusRobichon could you please test with recent version of FroshTools?

**Comment by MarcusRobichon** [comment]
Perfect! The Update fixes the problem. The cache sizes are shown now!

Thank you very much! Really, appreciate your work!

Marcus Robichon


Von: tinect ***@***.***>
Gesendet: Donnerstag, 21. Juli 2022 13:09
An: FriendsOfShopware/FroshTools ***@***.***>
Cc: Marcus Robichon ***@***.***>; Mention ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshTools] Cache size unknown with redis (?) (Issue #93)


Hey @MarcusRobichon<https://github.com/MarcusRobichon> could you please test with recent version of FroshTools?

-
