### ISSUE TITLE
Exception on overview page for missing opcache module

### ISSUE THREAD

**Issue by JonasDoebertin** [FriendsOfShopware/FroshTools#98]
### PHP Version

8.0.21

### Shopware Version

6.4.11.1

### Actual behaviour

Upon visiting the frosh tools admin page `/admin#/frosh/tools/index/index` the upper half of the page "System Status" loads, but the lower half "Performance" does not. Additionally the loader keeps spinning indefinitly.

Consulting the logs, I see the following error:

```
Uncaught Error: Frosh\Tools\Components\Health\SettingsResult::warning(): Argument #2 ($current) must be of type string, bool given,
called in /[redacted]/vendor/store.shopware.com/froshtools/src/Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php on line 53 {"exception":"[object] (TypeError(code: 0): Frosh\\Tools\\Components\\Health\\SettingsResult::warning(): Argument #2 ($current) must be of type string, bool given,
called in /[redacted]/vendor/store.shopware.com/froshtools/src/Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php on line 53 at /[redacted]/vendor/store.shopware.com/froshtools/src/Components/Health/SettingsResult.php:35)"} []
```

### Expected behaviour

The page should load completely an no error should be shown in the logs.

### Steps to Reproduce?

Seems to be a very specific error with the systems php configuration. The function at `Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php:L53` checks the `ini_get('opcache.enable_file_override')` value. This seems to return a boolean on this specific system where OpCache isn't even loaded as a module.

**Comment by wexotht** [comment]
@JonasDoebertin fixed in this PR: https://github.com/FriendsOfShopware/FroshTools/pull/96
